### ISSUE TITLE
Which presentation software do you use?

### ISSUE THREAD

**Issue by nipunsadvilkar** [jakevdp/website#4]
Hi @jakevdp , I have seen almost all of your talk from Pycon to Scipy and I like the way you give the talk and present it.
I just wanted to ask a question out of the curiosity: 
What presentation software do you use to make such a [pretty slides](https://speakerdeck.com/jakevdp/statistics-for-hackers)?

I am willing to give a talk at [Pycon India 2017](https://in.pycon.org/2017/) on [Probability for Hackers](https://github.com/nipunsadvilkar/ProbabilityForHackers) (inspired from your **Statistics for Hackers** talk). Your tips would be very helpful!
Thanks in advance.

P.S. - Excuse me for creating issue for such question.

**Comment by jakevdp** [comment]
I've used Google Slides for all my presentations in the last few years. I've found it to be a nice way to do WYSIWYG slide editing across platforms (I use both Linux and Mac), as well as to have automatic cloud backup as I progress. And with offline mode, it's even possible to work on them while flying to the conference, which I seem to be doing more and more of these days :smile:

**Comment by nipunsadvilkar** [comment]
@jakevdp Thanks a lot for replying. Would you also like to give some tips for my [Pycon India 2017](https://in.pycon.org/2017/) talk on [Probability for Hackers](https://github.com/nipunsadvilkar/ProbabilityForHackers)(inspired from your Statistics for Hackers talk)

**Comment by jakevdp** [comment]
I don't know exactly what direction you're going, but you might point out the discussion in the first chapter of Jaynes' book: he basically shows how the classical laws of probability follow directly from a few basic assumptions of how we might quantify knowledge about the world. It's a good way to frame the idea of probability as a means of encoding belief or knowledge.

**Comment by nipunsadvilkar** [comment]
Thanks for the suggestion. I would like to share details of talk soon with you to listen to your invaluable feedback.

Again, thanks for your generous help. :smile:
